import { useEffect, useRef, useState } from "react";
import type { ActionFunctionArgs, LoaderFunctionArgs } from "@remix-run/node";
import { json } from "@remix-run/node";
import { useFetcher, useLoaderData } from "@remix-run/react";
import { TitleBar } from "@shopify/app-bridge-react";
import { authenticate } from "../shopify.server";
import {
  getCurrentMRR,
  getAllTimeRevenue,
  getActiveSubscriptionCount,
  getRecentRevenueEvents,
} from "../lib/mrr.server";

// ── Loader ────────────────────────────────────────────────────────────────────
export const loader = async ({ request }: LoaderFunctionArgs) => {
  const { admin } = await authenticate.admin(request);

  const shopRes = await admin.graphql(`
    query GarcarDash {
      shop {
        name
        email
        plan { displayName }
        currencyCode
        primaryDomain { url }
      }
      products(first: 250) { edges { node { id } } }
      orders(first: 250, query: "financial_status:paid") {
        edges { node { id totalPriceSet { shopMoney { amount } } } }
      }
    }
  `);
  const shopData  = await shopRes.json();
  const shop      = shopData.data?.shop ?? {};
  const orders    = shopData.data?.orders?.edges ?? [];
  const products  = shopData.data?.products?.edges ?? [];

  const shopifyRevenue = orders.reduce((acc: number, e: any) =>
    acc + parseFloat(e.node.totalPriceSet?.shopMoney?.amount ?? "0"), 0);

  const [mrrCents, allTimeCents, activeSubs, recentEvents] = await Promise.all([
    getCurrentMRR(),
    getAllTimeRevenue(),
    getActiveSubscriptionCount(),
    getRecentRevenueEvents(8),
  ]);

  return json({
    shop,
    metrics: {
      shopifyRevenue:    shopifyRevenue.toFixed(2),
      shopifyOrders:     orders.length,
      shopifyProducts:   products.length,
      mrrCents,
      mrrDollars:        (mrrCents / 100).toFixed(2),
      allTimeDollars:    (allTimeCents / 100).toFixed(2),
      activeSubs,
      arTarget:          155000,
    },
    recentEvents: recentEvents.map(e => ({
      ...e,
      amountDollars: (e.amountCents / 100).toFixed(2),
      createdAt:     e.createdAt.toISOString(),
    })),
    webhookUrl: `${process.env.SHOPIFY_APP_URL ?? "https://your-app.railway.app"}/webhooks/stripe`,
  });
};

// ── Action ────────────────────────────────────────────────────────────────────
export const action = async ({ request }: ActionFunctionArgs) => {
  const { admin } = await authenticate.admin(request);
  const form   = await request.formData();
  const intent = form.get("intent");

  if (intent === "generate_product") {
    const r = await admin.graphql(`
      mutation CreateProduct($input: ProductInput!) {
        productCreate(input: $input) {
          product { id title handle }
          userErrors { field message }
        }
      }
    `, {
      variables: {
        input: {
          title: `Garcar AI Product — ${new Date().toLocaleDateString("en-US", {month:"short",day:"numeric",year:"numeric"})}`,
          descriptionHtml: `<p>Auto-generated by <strong>Garcar Enterprise Revenue Engine</strong>.</p>`,
          status: "DRAFT",
          tags: ["garcar-ai", "auto-generated"],
        },
      },
    });
    const d = await r.json();
    return json({ ok: true, product: d.data?.productCreate?.product });
  }

  return json({ ok: true });
};

// ── Helpers ───────────────────────────────────────────────────────────────────
function fmtDollar(val: string | number): string {
  const n = typeof val === "string" ? parseFloat(val) : val;
  return "$" + n.toFixed(2).replace(/\B(?=(\d{3})+(?!\d))/g, ",");
}

function eventLabel(type: string): string {
  const map: Record<string, string> = {
    "checkout.session.completed":    "Checkout Paid",
    "invoice.payment_succeeded":     "Invoice Paid",
    "invoice.payment_failed":        "Invoice Failed",
    "customer.subscription.created": "New Sub",
    "customer.subscription.updated": "Sub Updated",
    "customer.subscription.deleted": "Sub Cancelled",
    "charge.refunded":               "Refund",
  };
  return map[type] ?? type;
}

function eventBadgeClass(type: string): string {
  if (type.includes("failed") || type.includes("deleted") || type.includes("refunded"))
    return "gc-badge--alert";
  if (type.includes("updated")) return "gc-badge--info";
  return "gc-badge--live";
}

// ── Hex Logo SVG ──────────────────────────────────────────────────────────────
function GarcarHexLogo({ size = 52 }: { size?: number }) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 52 52"
      fill="none"
      aria-label="Garcar Enterprise Logo"
      className="gc-hex-logo"
    >
      {/* Hexagon outline */}
      <polygon
        points="26,3 48,14.5 48,37.5 26,49 4,37.5 4,14.5"
        stroke="#00ff88"
        strokeWidth="1.5"
        fill="rgba(0,255,136,0.06)"
      />
      {/* Inner hex */}
      <polygon
        points="26,10 40,18 40,34 26,42 12,34 12,18"
        stroke="#00e5d0"
        strokeWidth="0.8"
        fill="rgba(0,229,208,0.04)"
        opacity="0.7"
      />
      {/* G mark */}
      <text
        x="26"
        y="32"
        textAnchor="middle"
        fontFamily="'Syne', sans-serif"
        fontWeight="800"
        fontSize="18"
        fill="#00ff88"
        letterSpacing="-1"
      >
        G
      </text>
      {/* Corner dots */}
      <circle cx="26" cy="3"  r="2" fill="#00ff88" opacity="0.8" />
      <circle cx="48" cy="14.5" r="1.5" fill="#00e5d0" opacity="0.6" />
      <circle cx="48" cy="37.5" r="1.5" fill="#00e5d0" opacity="0.6" />
      <circle cx="26" cy="49" r="2" fill="#00ff88" opacity="0.8" />
      <circle cx="4"  cy="37.5" r="1.5" fill="#00e5d0" opacity="0.6" />
      <circle cx="4"  cy="14.5" r="1.5" fill="#00e5d0" opacity="0.6" />
    </svg>
  );
}

// ── Sparkline ─────────────────────────────────────────────────────────────────
function Sparkline({ heights, color }: { heights: number[]; color: string }) {
  return (
    <div className="gc-kpi__spark" style={{ height: 32 }}>
      {heights.map((h, i) => (
        <div
          key={i}
          className={`gc-kpi__spark-bar gc-kpi__spark-bar--${color}`}
          style={{ height: `${h}%`, transition: `height ${0.6 + i * 0.12}s cubic-bezier(0.34,1.56,0.64,1)` }}
        />
      ))}
    </div>
  );
}

// ── Animated Counter Hook ─────────────────────────────────────────────────────
function useAnimatedCounter(
  ref: React.MutableRefObject<HTMLSpanElement | null>,
  target: number,
  isDollar: boolean,
  delay = 0
) {
  useEffect(() => {
    const el = ref.current;
    if (!el) return;
    const duration = 2200;
    const startTime = performance.now() + delay;
    const step = (now: number) => {
      if (now < startTime) { requestAnimationFrame(step); return; }
      const p = Math.min((now - startTime) / duration, 1);
      const ease = 1 - Math.pow(1 - p, 4);
      const val = target * ease;
      el.textContent = isDollar
        ? "$" + val.toFixed(2).replace(/\B(?=(\d{3})+(?!\d))/g, ",")
        : Math.floor(val).toLocaleString();
      if (p < 1) requestAnimationFrame(step);
    };
    requestAnimationFrame(step);
  }, [target, delay]);
}

// ── Component ─────────────────────────────────────────────────────────────────
export default function CommandCenter() {
  const { shop, metrics, recentEvents, webhookUrl } = useLoaderData<typeof loader>();
  const fetcher = useFetcher<typeof action>();
  const loading = fetcher.state !== "idle";
  const product = (fetcher.data as any)?.product;

  // Clock
  const [clock, setClock] = useState(() => new Date().toLocaleTimeString("en-US", { hour12: false }));
  useEffect(() => {
    const t = setInterval(() => {
      setClock(new Date().toLocaleTimeString("en-US", { hour12: false }));
    }, 1000);
    return () => clearInterval(t);
  }, []);

  // Webhook banner collapse
  const [webhookOpen, setWebhookOpen] = useState(false);

  // Copy state
  const [copied, setCopied] = useState(false);
  const handleCopy = () => {
    navigator.clipboard?.writeText(webhookUrl).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  // Counter refs
  const mrrRef      = useRef<HTMLSpanElement>(null);
  const allTimeRef  = useRef<HTMLSpanElement>(null);
  const subsRef     = useRef<HTMLSpanElement>(null);
  const arrRef      = useRef<HTMLSpanElement>(null);
  const shopRevRef  = useRef<HTMLSpanElement>(null);
  const ordersRef   = useRef<HTMLSpanElement>(null);

  useAnimatedCounter(mrrRef,     parseFloat(metrics.mrrDollars),     true,  100);
  useAnimatedCounter(allTimeRef, parseFloat(metrics.allTimeDollars), true,  200);
  useAnimatedCounter(subsRef,    metrics.activeSubs,                 false, 300);
  useAnimatedCounter(arrRef,     metrics.arTarget,                   false, 150);
  useAnimatedCounter(shopRevRef, parseFloat(metrics.shopifyRevenue), true,  250);
  useAnimatedCounter(ordersRef,  metrics.shopifyOrders,              false, 350);

  // Progress bar animation
  useEffect(() => {
    const t = setTimeout(() => {
      document.querySelectorAll<HTMLElement>(".gc-progress-fill[data-pct]").forEach(b => {
        b.style.width = (b.dataset.pct ?? "0") + "%";
      });
      document.querySelectorAll<HTMLElement>(".gc-revenue-bar__segment[data-w]").forEach(b => {
        b.style.width = (b.dataset.w ?? "0") + "%";
      });
    }, 500);
    return () => clearTimeout(t);
  }, []);

  // Scroll reveal
  useEffect(() => {
    const els = document.querySelectorAll(".gc-reveal");
    const obs = new IntersectionObserver(entries => {
      entries.forEach(e => { if (e.isIntersecting) e.target.classList.add("gc-reveal--in"); });
    }, { threshold: 0.05 });
    els.forEach(el => obs.observe(el));
    return () => obs.disconnect();
  }, []);

  // ARR progress %
  const arrPct = Math.min(
    ((parseFloat(metrics.mrrDollars) * 12) / metrics.arTarget) * 100,
    100
  ).toFixed(1);

  // Revenue pipeline segments
  const totalPipeline = 49 + 97 + 11 + 8; // $K
  const pipeSegments = [
    { label: "NWU Protocol",   amount: 49, cls: "--nwu",     color: "#00ff88" },
    { label: "Garcar Suite",   amount: 97, cls: "--suite",   color: "#00e5d0" },
    { label: "Shopify App",    amount: 11, cls: "--shopify",  color: "#9b59b6" },
    { label: "Other",          amount: 8,  cls: "--other",   color: "#3d5a70" },
  ];

  // System status grid data
  const systems = [
    { name: "Stripe Webhooks",    state: "on",   uptime: "99.9%" },
    { name: "Shopify Integration",state: "on",   uptime: "100%"  },
    { name: "Prisma DB",          state: "on",   uptime: "99.7%" },
    { name: "Railway Deploy",     state: "on",   uptime: "98.2%" },
    { name: "GitHub Actions",     state: "warn", uptime: "96.1%" },
    { name: "Vercel Apps",        state: "on",   uptime: "99.8%" },
  ];

  // Webhook events
  const webhookEvents = [
    "checkout.session.completed",
    "invoice.payment_succeeded",
    "invoice.payment_failed",
    "customer.subscription.created",
    "customer.subscription.updated",
    "customer.subscription.deleted",
    "charge.refunded",
  ];

  return (
    <div className="gc-root gc-canvas">
      {/* Ambient layers */}
      <div className="gc-grid-bg" />
      <div className="gc-orb gc-orb--1" />
      <div className="gc-orb gc-orb--2" />
      <div className="gc-orb gc-orb--3" />

      <TitleBar title="Garcar Enterprise Command Center" />

      <div className="gc-content">

        {/* ══════════════════════════════════════════════════
            HERO HEADER ROW
        ═══════════════════════════════════════════════════ */}
        <header className="gc-header gc-enter">
          {/* Brand identity */}
          <div className="gc-logo">
            <div className="gc-logo__hex-wrap">
              <GarcarHexLogo size={48} />
            </div>
            <div>
              <div className="gc-command-title" aria-label="Garcar Command Center">
                {"GARCAR COMMAND CENTER".split("").map((ch, i) => (
                  <span
                    key={i}
                    className="char"
                    style={{ "--char-index": i } as React.CSSProperties}
                  >
                    {ch === " " ? "\u00a0" : ch}
                  </span>
                ))}
              </div>
              <span className="gc-logo__sub">
                Shopify + Stripe Revenue Intelligence · {shop?.name ?? "Empire"}
              </span>
            </div>
          </div>

          {/* Right meta */}
          <div className="gc-header__right">
            {/* Live clock */}
            <span className="gc-clock">{clock}</span>

            {/* Live status */}
            <span className="gc-live-pill">
              <span className="gc-live-dot" />
              ALL SYSTEMS LIVE
            </span>

            {/* System status badge */}
            <span className="gc-badge gc-badge--live gc-badge--dot">
              Stripe Active
            </span>
          </div>
        </header>

        {/* ══════════════════════════════════════════════════
            EMPIRE KPI ROW — 5 metric cards
        ═══════════════════════════════════════════════════ */}
        <div className="gc-kpi-row gc-stagger">

          {/* MRR This Month */}
          <div className="gc-kpi">
            <div className="gc-kpi__label">MRR — This Month</div>
            <div className="gc-kpi__value">
              <span ref={mrrRef}>$0.00</span>
            </div>
            <div className="gc-kpi__delta gc-kpi__delta--up">↑ Live from Stripe webhooks</div>
            <Sparkline heights={[20, 35, 45, 60, 80]} color="emerald" />
          </div>

          {/* ARR Target Progress */}
          <div className="gc-kpi">
            <div className="gc-kpi__label">ARR Target Progress</div>
            <div className="gc-kpi__value gc-kpi__value--teal">
              {arrPct}%
            </div>
            <div className="gc-kpi__delta gc-kpi__delta--flat">
              Target: ${metrics.arTarget.toLocaleString()}/yr
            </div>
            <Sparkline heights={[15, 25, 30, 42, 55]} color="teal" />
          </div>

          {/* All-Time Revenue */}
          <div className="gc-kpi">
            <div className="gc-kpi__label">All-Time Revenue</div>
            <div className="gc-kpi__value gc-kpi__value--gold">
              <span ref={allTimeRef}>$0.00</span>
            </div>
            <div className="gc-kpi__delta gc-kpi__delta--up">↑ Checkout + invoice events</div>
            <Sparkline heights={[30, 42, 55, 70, 90]} color="gold" />
          </div>

          {/* Active Subscriptions */}
          <div className="gc-kpi">
            <div className="gc-kpi__label">Active Subscriptions</div>
            <div className="gc-kpi__value">
              <span ref={subsRef}>0</span>
            </div>
            <div className="gc-kpi__delta gc-kpi__delta--flat">→ Prisma · live sync</div>
            <Sparkline heights={[10, 20, 30, 40, 50]} color="emerald" />
          </div>

          {/* Shopify Revenue */}
          <div className="gc-kpi">
            <div className="gc-kpi__label">Shopify Revenue</div>
            <div className="gc-kpi__value gc-kpi__value--teal">
              <span ref={shopRevRef}>$0.00</span>
            </div>
            <div className="gc-kpi__delta gc-kpi__delta--up">↑ {metrics.shopifyOrders} paid orders</div>
            <Sparkline heights={[25, 38, 48, 62, 75]} color="cyan" />
          </div>
        </div>

        {/* ══════════════════════════════════════════════════
            REVENUE PIPELINE VISUALIZATION
        ═══════════════════════════════════════════════════ */}
        <div className="gc-card gc-reveal" style={{ marginBottom: "var(--gc-space-6)" }}>
          <div className="gc-card__header">
            <span className="gc-card__title">Revenue Pipeline — Path to $155K/mo</span>
            <span className="gc-badge gc-badge--info">
              ${totalPipeline}K Pipeline
            </span>
          </div>
          <div className="gc-card__body">
            {/* ARR progress bar */}
            <div className="gc-arr-label">
              <span
                className="gc-mono"
                style={{ fontSize: "0.72rem", color: "var(--gc-text-3)" }}
              >
                MRR: {fmtDollar(metrics.mrrDollars)} / month
              </span>
              <span className="gc-arr-pct">{arrPct}% to ARR target</span>
            </div>
            <div className="gc-progress gc-progress--lg" style={{ marginBottom: "var(--gc-space-5)" }}>
              <div
                className="gc-progress-fill"
                data-pct={arrPct}
                style={{ width: "0%" }}
              />
            </div>

            {/* Stacked revenue bar */}
            <div
              className="gc-mono"
              style={{ fontSize: "0.65rem", color: "var(--gc-text-3)", letterSpacing: "0.12em", textTransform: "uppercase", marginBottom: "var(--gc-space-2)" }}
            >
              Revenue Segments
            </div>
            <div className="gc-revenue-bar">
              {pipeSegments.map((seg) => (
                <div
                  key={seg.label}
                  className={`gc-revenue-bar__segment gc-revenue-bar__segment${seg.cls}`}
                  data-w={String((seg.amount / totalPipeline) * 100)}
                  style={{ width: "0%" }}
                  title={`${seg.label}: $${seg.amount}K`}
                >
                  {seg.label}
                </div>
              ))}
            </div>

            {/* Labels */}
            <div className="gc-revenue-bar__labels" style={{ marginTop: "var(--gc-space-3)" }}>
              {pipeSegments.map((seg) => (
                <div key={seg.label} className="gc-revenue-bar__label">
                  <div
                    className="gc-revenue-bar__dot"
                    style={{ background: seg.color }}
                  />
                  <span>{seg.label}</span>
                  <span style={{ color: "var(--gc-text)" }}>${seg.amount}K</span>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* ══════════════════════════════════════════════════
            MAIN GRID — live feed + sidebar
        ═══════════════════════════════════════════════════ */}
        <div className="gc-grid gc-grid--sidebar">

          {/* ── LEFT COLUMN ── */}
          <div style={{ display: "flex", flexDirection: "column", gap: "var(--gc-space-4)" }}>

            {/* Live Revenue Feed Table */}
            <div className="gc-card gc-reveal">
              <div className="gc-card__header">
                <div style={{ display: "flex", alignItems: "center", gap: "var(--gc-space-3)" }}>
                  <span className="gc-live-dot" />
                  <span className="gc-card__title">Live Revenue Feed</span>
                </div>
                <span className="gc-badge gc-badge--live gc-badge--dot">
                  Real-time
                </span>
              </div>
              <div className="gc-card__body" style={{ padding: 0 }}>
                {recentEvents.length === 0 ? (
                  <div className="gc-empty">
                    <div className="gc-empty__icon">⚡</div>
                    <div className="gc-empty__title">Waiting for first Stripe event</div>
                    <div className="gc-empty__body">
                      Register webhook at dashboard.stripe.com/webhooks<br />
                      <span style={{ color: "var(--gc-emerald)" }}>{webhookUrl}</span>
                    </div>
                  </div>
                ) : (
                  <table className="gc-table">
                    <thead>
                      <tr>
                        <th>Event</th>
                        <th>Customer</th>
                        <th>Product</th>
                        <th style={{ textAlign: "right" }}>Amount</th>
                        <th>Time</th>
                      </tr>
                    </thead>
                    <tbody>
                      {recentEvents.map((evt: any) => (
                        <tr key={evt.id}>
                          <td>
                            <span className={`gc-badge ${eventBadgeClass(evt.eventType)}`}>
                              {eventLabel(evt.eventType)}
                            </span>
                          </td>
                          <td
                            style={{
                              fontFamily: "var(--gc-font-mono)",
                              fontSize: "0.74rem",
                              maxWidth: 140,
                              overflow: "hidden",
                              textOverflow: "ellipsis",
                              whiteSpace: "nowrap",
                            }}
                          >
                            {evt.customerEmail ?? evt.customerId ?? "—"}
                          </td>
                          <td style={{ color: "var(--gc-text)" }}>
                            {evt.productName ?? "—"}
                          </td>
                          <td
                            className="gc-table__amount"
                            style={{
                              textAlign: "right",
                              color: parseFloat(evt.amountDollars) < 0
                                ? "var(--gc-red)"
                                : "var(--gc-emerald)",
                            }}
                          >
                            {parseFloat(evt.amountDollars) < 0 ? "-" : "+"}
                            ${Math.abs(parseFloat(evt.amountDollars)).toFixed(2)}{" "}
                            <span style={{ color: "var(--gc-text-3)", fontSize: "0.65rem" }}>
                              {evt.currency}
                            </span>
                          </td>
                          <td
                            style={{
                              fontFamily: "var(--gc-font-mono)",
                              fontSize: "0.7rem",
                              color: "var(--gc-text-3)",
                              whiteSpace: "nowrap",
                            }}
                          >
                            {new Date(evt.createdAt).toLocaleDateString("en-US", {
                              month: "short",
                              day: "numeric",
                              hour: "2-digit",
                              minute: "2-digit",
                            })}
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                )}
              </div>
            </div>

            {/* System Status Grid 3×2 */}
            <div className="gc-card gc-reveal">
              <div className="gc-card__header">
                <span className="gc-card__title">System Status</span>
                <span className="gc-badge gc-badge--live gc-badge--dot">
                  All Systems
                </span>
              </div>
              <div className="gc-card__body">
                <div className="gc-system-grid">
                  {systems.map((sys) => (
                    <div key={sys.name} className="gc-system-card">
                      <div className="gc-system-card__top">
                        <span className="gc-system-card__name">{sys.name}</span>
                        <span className={`gc-status-dot gc-status-dot--${sys.state}`} />
                      </div>
                      <div className="gc-system-card__uptime">
                        Uptime: <span style={{ color: "var(--gc-text-2)" }}>{sys.uptime}</span>
                      </div>
                      <div style={{ marginTop: 8 }}>
                        <div className="gc-progress" style={{ height: 3 }}>
                          <div
                            className="gc-progress-fill"
                            data-pct={sys.uptime.replace("%", "")}
                            style={{ width: "0%", height: 3 }}
                          />
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </div>

            {/* Webhook Setup Banner */}
            <div className={`gc-webhook-banner gc-reveal ${webhookOpen ? "gc-webhook-banner--open" : ""}`}>
              <div
                className="gc-webhook-banner__header"
                onClick={() => setWebhookOpen(v => !v)}
                role="button"
                aria-expanded={webhookOpen}
              >
                <div style={{ display: "flex", alignItems: "center", gap: "var(--gc-space-3)" }}>
                  <span className="gc-live-dot" />
                  <span className="gc-webhook-banner__title">Stripe Webhook Configuration</span>
                </div>
                <div style={{ display: "flex", alignItems: "center", gap: "var(--gc-space-3)" }}>
                  <span className="gc-badge gc-badge--live">Wired</span>
                  <span
                    className="gc-collapse-chevron"
                    style={{ transform: webhookOpen ? "rotate(180deg)" : "none", transition: "transform 0.2s ease" }}
                  >
                    ▾
                  </span>
                </div>
              </div>
              <div className="gc-webhook-banner__body">
                <div className="gc-webhook-banner__url">
                  <span style={{ flex: 1 }}>{webhookUrl}</span>
                  <button
                    className={`gc-copy-btn ${copied ? "gc-copy-btn--copied" : ""}`}
                    onClick={handleCopy}
                    type="button"
                  >
                    {copied ? "✓ Copied" : "Copy"}
                  </button>
                </div>
                <div
                  className="gc-mono"
                  style={{ fontSize: "0.65rem", color: "var(--gc-text-3)", letterSpacing: "0.12em", textTransform: "uppercase", marginBottom: "var(--gc-space-2)" }}
                >
                  Registered Events (7)
                </div>
                {webhookEvents.map(e => (
                  <div key={e} className="gc-webhook-event">{e}</div>
                ))}
              </div>
            </div>

            {/* Quick Actions Row */}
            <div className="gc-card gc-reveal">
              <div className="gc-card__header">
                <span className="gc-card__title">Quick Actions</span>
              </div>
              <div className="gc-card__body">
                <div className="gc-actions-row">
                  <fetcher.Form method="POST">
                    <input type="hidden" name="intent" value="generate_product" />
                    <button
                      type="submit"
                      className={`gc-btn gc-btn--primary${loading ? " gc-btn--loading" : ""}`}
                    >
                      {loading ? "⟳ Generating…" : "⚡ Generate Product"}
                    </button>
                  </fetcher.Form>
                  <a
                    href="https://dashboard.stripe.com/payments"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="gc-btn gc-btn--ghost"
                  >
                    Stripe Dashboard →
                  </a>
                  <a
                    href="https://railway.app"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="gc-btn gc-btn--ghost"
                  >
                    Open Railway →
                  </a>
                  <a
                    href="https://github.com/Garrettc123/garcar-shopify-app"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="gc-btn gc-btn--ghost"
                  >
                    View GitHub →
                  </a>
                </div>
                {product && (
                  <div className="gc-result-box" style={{ marginTop: "var(--gc-space-3)" }}>
                    ✅ Product created: <strong>{product.title}</strong>
                  </div>
                )}
              </div>
            </div>
          </div>

          {/* ── RIGHT SIDEBAR ── */}
          <div style={{ display: "flex", flexDirection: "column", gap: "var(--gc-space-4)" }}>

            {/* MRR Hero Card */}
            <div
              className="gc-card gc-reveal"
              style={{
                background: "rgba(0,255,136,0.03)",
                borderColor: "rgba(0,255,136,0.2)",
              }}
            >
              <div className="gc-card__body" style={{ textAlign: "center", padding: "var(--gc-space-8) var(--gc-space-5)" }}>
                <div
                  className="gc-mono"
                  style={{
                    fontSize: "0.62rem",
                    color: "var(--gc-text-3)",
                    textTransform: "uppercase",
                    letterSpacing: "0.18em",
                    marginBottom: 8,
                  }}
                >
                  Stripe MRR · This Month
                </div>
                <div
                  style={{
                    fontFamily: "var(--gc-font-display)",
                    fontSize: "3rem",
                    fontWeight: 900,
                    background: "linear-gradient(135deg, #00ff88 0%, #00e5d0 100%)",
                    WebkitBackgroundClip: "text",
                    WebkitTextFillColor: "transparent",
                    backgroundClip: "text",
                    letterSpacing: "-0.04em",
                    lineHeight: 1,
                    marginBottom: 10,
                  }}
                >
                  {fmtDollar(metrics.mrrDollars)}
                </div>
                <div
                  className="gc-mono"
                  style={{ fontSize: "0.7rem", color: "var(--gc-text-3)", marginBottom: 16 }}
                >
                  {metrics.activeSubs} active sub{metrics.activeSubs !== 1 ? "s" : ""} ·
                  all-time {fmtDollar(metrics.allTimeDollars)}
                </div>
                <div style={{ height: 1, background: "var(--gc-border-subtle)", marginBottom: 14 }} />
                <div className="gc-mono" style={{ fontSize: "0.7rem", color: "var(--gc-text-3)" }}>
                  ARR target:{" "}
                  <span style={{ color: "var(--gc-emerald)", fontWeight: 700 }}>
                    ${metrics.arTarget.toLocaleString()}/yr
                  </span>
                </div>
                <div style={{ marginTop: 12 }}>
                  <div className="gc-progress">
                    <div
                      className="gc-progress-fill"
                      data-pct={arrPct}
                      style={{ width: "0%" }}
                    />
                  </div>
                  <div
                    className="gc-mono"
                    style={{ fontSize: "0.65rem", color: "var(--gc-text-3)", marginTop: 4, textAlign: "right" }}
                  >
                    {arrPct}% complete
                  </div>
                </div>
              </div>
            </div>

            {/* Store Info */}
            <div className="gc-card gc-reveal">
              <div className="gc-card__header">
                <span className="gc-card__title">Store</span>
                <span className="gc-badge gc-badge--live gc-badge--dot">Connected</span>
              </div>
              <div className="gc-card__body">
                <div className="gc-status-list">
                  {[
                    { label: "Name",     val: shop?.name },
                    { label: "Plan",     val: shop?.plan?.displayName },
                    { label: "Currency", val: shop?.currencyCode },
                    { label: "Domain",   val: shop?.primaryDomain?.url?.replace("https://", "") },
                    { label: "Products", val: String(metrics.shopifyProducts) },
                    { label: "Orders",   val: `${metrics.shopifyOrders} paid` },
                  ].map((r, i) => (
                    <div key={i} className="gc-status-row">
                      <span className="gc-status-name">{r.label}</span>
                      <span className="gc-status-val">{r.val || "—"}</span>
                    </div>
                  ))}
                </div>
              </div>
            </div>

            {/* Full System Status Detail */}
            <div className="gc-card gc-reveal">
              <div className="gc-card__header">
                <span className="gc-card__title">Infrastructure</span>
              </div>
              <div className="gc-card__body">
                <div className="gc-status-list">
                  {[
                    { label: "Stripe Webhook",    state: "on",   val: "Live · HMAC ✅" },
                    { label: "MRR Tracking",      state: "on",   val: "Prisma · Real-time" },
                    { label: "Subscription Sync", state: "on",   val: "Auto-upsert" },
                    { label: "Refund Handling",   state: "on",   val: "Negative events" },
                    { label: "Idempotency",       state: "on",   val: "stripeEventId key" },
                    { label: "OAuth",             state: "on",   val: "Active" },
                    { label: "Admin GraphQL",     state: "on",   val: "2026-01" },
                    { label: "Churn Predictor",   state: "on",   val: "Vercel · Live" },
                    { label: "Deal Desk AI",      state: "on",   val: "Vercel · Live" },
                    { label: "Content Engine",    state: "on",   val: "Vercel · Live" },
                    { label: "GitHub CI",         state: "on",   val: "Passing" },
                    { label: "Stripe Compliance", state: "warn", val: "Due Apr 14" },
                    { label: "garcar.ai DNS",     state: "off",  val: "NXDOMAIN" },
                  ].map((s, i) => (
                    <div key={i} className="gc-status-row">
                      <span className="gc-status-name">
                        <span className={`gc-status-dot gc-status-dot--${s.state}`} />
                        {s.label}
                      </span>
                      <span className="gc-status-val">{s.val}</span>
                    </div>
                  ))}
                </div>
              </div>
            </div>

            {/* Webhook endpoint card */}
            <div
              className="gc-card gc-reveal"
              style={{ borderColor: "rgba(0,255,136,0.2)" }}
            >
              <div className="gc-card__header">
                <span className="gc-card__title">Stripe Webhook</span>
                <span className="gc-badge gc-badge--live gc-badge--dot">Wired</span>
              </div>
              <div className="gc-card__body">
                <div className="gc-status-list" style={{ marginBottom: 16 }}>
                  <div className="gc-status-row">
                    <span className="gc-status-name">
                      <span className="gc-status-dot gc-status-dot--on" />
                      Endpoint
                    </span>
                    <span className="gc-status-val">/webhooks/stripe</span>
                  </div>
                  <div className="gc-status-row">
                    <span className="gc-status-name">
                      <span className="gc-status-dot gc-status-dot--on" />
                      HMAC Verify
                    </span>
                    <span className="gc-status-val">SHA-256 ✅</span>
                  </div>
                  <div className="gc-status-row">
                    <span className="gc-status-name">
                      <span className="gc-status-dot gc-status-dot--on" />
                      Idempotency
                    </span>
                    <span className="gc-status-val">stripeEventId</span>
                  </div>
                </div>
                <div
                  className="gc-code"
                  style={{ display: "flex", alignItems: "flex-start", gap: 8 }}
                >
                  <span style={{ flex: 1, wordBreak: "break-all" }}>{webhookUrl}</span>
                  <button
                    className={`gc-copy-btn ${copied ? "gc-copy-btn--copied" : ""}`}
                    onClick={handleCopy}
                    type="button"
                    style={{ flexShrink: 0, marginTop: 2 }}
                  >
                    {copied ? "✓" : "Copy"}
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
