import { useEffect, useRef } from "react";
import type { ActionFunctionArgs, LoaderFunctionArgs } from "@remix-run/node";
import { json } from "@remix-run/node";
import { useFetcher, useLoaderData } from "@remix-run/react";
import { TitleBar } from "@shopify/app-bridge-react";
import { authenticate } from "../shopify.server";
import {
  getCurrentMRR,
  getAllTimeRevenue,
  getActiveSubscriptionCount,
  getRecentRevenueEvents,
} from "../lib/mrr.server";

// ── Loader ───────────────────────────────────────────────────────────────────
export const loader = async ({ request }: LoaderFunctionArgs) => {
  const { admin } = await authenticate.admin(request);

  // ── Shopify data ──
  const shopRes = await admin.graphql(`
    query GarcarDash {
      shop {
        name
        email
        plan { displayName }
        currencyCode
        primaryDomain { url }
      }
      products(first: 250) { edges { node { id } } }
      orders(first: 250, query: "financial_status:paid") {
        edges { node { id totalPriceSet { shopMoney { amount } } } }
      }
    }
  `);
  const shopData  = await shopRes.json();
  const shop      = shopData.data?.shop ?? {};
  const orders    = shopData.data?.orders?.edges ?? [];
  const products  = shopData.data?.products?.edges ?? [];

  const shopifyRevenue = orders.reduce((acc: number, e: any) =>
    acc + parseFloat(e.node.totalPriceSet?.shopMoney?.amount ?? "0"), 0);

  // ── Stripe / Prisma MRR data ──
  const [mrrCents, allTimeCents, activeSubs, recentEvents] = await Promise.all([
    getCurrentMRR(),
    getAllTimeRevenue(),
    getActiveSubscriptionCount(),
    getRecentRevenueEvents(8),
  ]);

  return json({
    shop,
    metrics: {
      shopifyRevenue:    shopifyRevenue.toFixed(2),
      shopifyOrders:     orders.length,
      shopifyProducts:   products.length,
      // Stripe MRR (from Prisma)
      mrrCents,
      mrrDollars:        (mrrCents / 100).toFixed(2),
      allTimeDollars:    (allTimeCents / 100).toFixed(2),
      activeSubs,
      // Garcar ARR target
      arTarget:          155000,
    },
    recentEvents: recentEvents.map(e => ({
      ...e,
      amountDollars: (e.amountCents / 100).toFixed(2),
      createdAt:     e.createdAt.toISOString(),
    })),
    webhookUrl: `${process.env.SHOPIFY_APP_URL ?? "https://your-app.railway.app"}/webhooks/stripe`,
  });
};

// ── Action ───────────────────────────────────────────────────────────────────
export const action = async ({ request }: ActionFunctionArgs) => {
  const { admin } = await authenticate.admin(request);
  const form   = await request.formData();
  const intent = form.get("intent");

  if (intent === "generate_product") {
    const r = await admin.graphql(`
      mutation CreateProduct($input: ProductInput!) {
        productCreate(input: $input) {
          product { id title handle }
          userErrors { field message }
        }
      }
    `, {
      variables: {
        input: {
          title: `Garcar AI Product — ${new Date().toLocaleDateString("en-US", {month:"short",day:"numeric",year:"numeric"})}`,
          descriptionHtml: `<p>Auto-generated by <strong>Garcar Enterprise Revenue Engine</strong>.</p>`,
          status: "DRAFT",
          tags: ["garcar-ai", "auto-generated"],
        },
      },
    });
    const d = await r.json();
    return json({ ok: true, product: d.data?.productCreate?.product });
  }

  return json({ ok: true });
};

// ── Helpers ───────────────────────────────────────────────────────────────────
function eventLabel(type: string) {
  const map: Record<string, string> = {
    "checkout.session.completed":   "💰 Checkout paid",
    "invoice.payment_succeeded":    "💳 Invoice paid",
    "invoice.payment_failed":       "⚠️  Invoice failed",
    "customer.subscription.created":"🆕 New subscription",
    "customer.subscription.updated":"🔄 Subscription updated",
    "customer.subscription.deleted":"❌ Subscription cancelled",
    "charge.refunded":              "🔙 Refund",
  };
  return map[type] ?? type;
}

function eventBadgeClass(type: string) {
  if (type.includes("failed") || type.includes("deleted") || type.includes("refunded")) return "gc-badge--alert";
  if (type.includes("updated")) return "gc-badge--info";
  return "gc-badge--live";
}

// ── Component ─────────────────────────────────────────────────────────────────
export default function CommandCenter() {
  const { shop, metrics, recentEvents, webhookUrl } = useLoaderData<typeof loader>();
  const fetcher  = useFetcher<typeof action>();
  const cRefs    = useRef<Record<string, HTMLSpanElement | null>>({});
  const loading  = fetcher.state !== "idle";
  const product  = (fetcher.data as any)?.product;

  // Animate counters
  useEffect(() => {
    const targets: Record<string, number> = {
      shopifyRevenue: parseFloat(metrics.shopifyRevenue),
      shopifyOrders:  metrics.shopifyOrders,
      shopifyProducts:metrics.shopifyProducts,
      mrrDollars:     parseFloat(metrics.mrrDollars),
      allTime:        parseFloat(metrics.allTimeDollars),
      activeSubs:     metrics.activeSubs,
      ar:             metrics.arTarget,
    };
    Object.entries(targets).forEach(([key, target]) => {
      const el = cRefs.current[key];
      if (!el) return;
      const isDollar  = ["shopifyRevenue","mrrDollars","allTime"].includes(key);
      const isInteger = !isDollar;
      const duration  = 2000;
      const start     = performance.now();
      const step = (now: number) => {
        const p   = Math.min((now - start) / duration, 1);
        const e   = 1 - Math.pow(1 - p, 4);
        const val = target * e;
        el.textContent = isDollar
          ? "$" + val.toFixed(2).replace(/\B(?=(\d{3})+(?!\d))/g, ",")
          : Math.floor(val).toLocaleString();
        if (p < 1) requestAnimationFrame(step);
      };
      requestAnimationFrame(step);
    });
  }, [metrics]);

  // Animate progress bars
  useEffect(() => {
    const t = setTimeout(() => {
      document.querySelectorAll<HTMLElement>(".gc-progress-fill[data-pct]").forEach(b => {
        b.style.width = b.dataset.pct + "%";
      });
    }, 400);
    return () => clearTimeout(t);
  }, []);

  // Reveal on scroll
  useEffect(() => {
    const els = document.querySelectorAll(".gc-reveal");
    const obs = new IntersectionObserver(entries => {
      entries.forEach(e => { if (e.isIntersecting) e.target.classList.add("gc-reveal--in"); });
    }, { threshold: 0.05 });
    els.forEach(el => obs.observe(el));
    return () => obs.disconnect();
  }, []);

  const revenueProducts = [
    { name: "Churn Predictor AI",        model: "B2B SaaS",        status: "live",  mrr: 25000 },
    { name: "Deal Desk AI",              model: "Per-proposal",    status: "live",  mrr: 18000 },
    { name: "Content Engine AI",         model: "SaaS",            status: "live",  mrr: 22000 },
    { name: "MAUT Decision Engine",      model: "SaaS",            status: "live",  mrr: 97    },
    { name: "NWU Protocol — Basic",      model: "Subscription",    status: "live",  mrr: 49    },
    { name: "NWU Protocol — Premium",    model: "Subscription",    status: "live",  mrr: 149   },
    { name: "NWU Protocol — Enterprise", model: "Subscription",    status: "live",  mrr: 499   },
    { name: "AI Growth Engine",          model: "Managed Service", status: "live",  mrr: 1497  },
    { name: "Revenue Recovery Sprint",   model: "Weekly",          status: "live",  mrr: 497   },
    { name: "Smart Contract Auditor",    model: "API + SaaS",      status: "build", mrr: 25000 },
    { name: "DeFi Yield Aggregator",     model: "% Yield",         status: "build", mrr: 30000 },
    { name: "Lead Enrichment Engine",    model: "Usage API",       status: "build", mrr: 20000 },
  ];

  const hasStripeRevenue = parseFloat(metrics.mrrDollars) > 0;

  return (
    <div className="gc-root gc-canvas">
      <div className="gc-grid-bg" />
      <div className="gc-orb gc-orb--1" />
      <div className="gc-orb gc-orb--2" />
      <div className="gc-orb gc-orb--3" />

      <TitleBar title="Garcar Enterprise" />

      <div className="gc-content">

        {/* ── Header ── */}
        <header className="gc-header gc-reveal">
          <div className="gc-logo">
            <div className="gc-logo__hex">⬡</div>
            <div>
              <div className="gc-logo__text">Garcar Enterprise</div>
              <span className="gc-logo__sub">Shopify + Stripe Revenue Command Center</span>
            </div>
          </div>
          <div className="gc-header__right">
            <span className="gc-live-pill"><span className="gc-live-dot" />Stripe Webhook Active</span>
            <span className="gc-shop-name">{shop?.name}</span>
          </div>
        </header>

        {/* ── Stripe MRR Banner ── */}
        {hasStripeRevenue ? (
          <div className="gc-reveal" style={{
            marginBottom: "24px",
            padding: "16px 22px",
            background: "rgba(0,255,136,0.05)",
            border: "1px solid rgba(0,255,136,0.25)",
            borderRadius: "14px",
            display: "flex",
            alignItems: "center",
            gap: "14px",
          }}>
            <span style={{ fontSize: "1.4rem" }}>💰</span>
            <div>
              <div style={{ fontFamily: "var(--gc-font-display)", fontWeight: 700, color: "var(--gc-emerald)" }}>
                ${metrics.mrrDollars} MRR collected this month via Stripe
              </div>
              <div style={{ fontSize: "0.78rem", color: "var(--gc-text-3)", fontFamily: "var(--gc-font-mono)" }}>
                All-time: ${metrics.allTimeDollars} · {metrics.activeSubs} active subscriptions
              </div>
            </div>
          </div>
        ) : (
          <div className="gc-reveal" style={{
            marginBottom: "24px",
            padding: "14px 22px",
            background: "rgba(245,197,24,0.04)",
            border: "1px solid rgba(245,197,24,0.2)",
            borderRadius: "14px",
            display: "flex",
            alignItems: "center",
            gap: "14px",
          }}>
            <span style={{ fontSize: "1.2rem" }}>⚡</span>
            <div>
              <div style={{ fontWeight: 600, color: "var(--gc-gold)", fontSize: "0.9rem" }}>
                Stripe webhook is live — waiting for first payment
              </div>
              <div style={{ fontSize: "0.75rem", color: "var(--gc-text-3)", fontFamily: "var(--gc-font-mono)", marginTop: "2px" }}>
                Endpoint: {webhookUrl}
              </div>
            </div>
          </div>
        )}

        {/* ── KPI Row ── */}
        <div className="gc-kpi-row gc-stagger">
          <div className="gc-kpi">
            <div className="gc-kpi__label">Stripe MRR (This Month)</div>
            <div className="gc-kpi__value gc-counter">
              <span ref={el => { cRefs.current.mrrDollars = el; }}>$0.00</span>
            </div>
            <div className="gc-kpi__delta gc-kpi__delta--up">↑ Live from Stripe webhooks</div>
            <div className="gc-kpi__spark gc-kpi__spark--green" />
          </div>
          <div className="gc-kpi">
            <div className="gc-kpi__label">All-Time Revenue</div>
            <div className="gc-kpi__value gc-counter">
              <span ref={el => { cRefs.current.allTime = el; }}>$0.00</span>
            </div>
            <div className="gc-kpi__delta gc-kpi__delta--up">↑ checkout + invoice events</div>
            <div className="gc-kpi__spark gc-kpi__spark--cyan" />
          </div>
          <div className="gc-kpi">
            <div className="gc-kpi__label">Active Subscriptions</div>
            <div className="gc-kpi__value gc-counter">
              <span ref={el => { cRefs.current.activeSubs = el; }}>0</span>
            </div>
            <div className="gc-kpi__delta gc-kpi__delta--flat">→ Prisma · live sync</div>
            <div className="gc-kpi__spark gc-kpi__spark--gold" />
          </div>
          <div className="gc-kpi">
            <div className="gc-kpi__label">Shopify Store Orders</div>
            <div className="gc-kpi__value gc-counter">
              <span ref={el => { cRefs.current.shopifyOrders = el; }}>0</span>
            </div>
            <div className="gc-kpi__delta gc-kpi__delta--up">↑ Admin GraphQL · paid</div>
            <div className="gc-kpi__spark gc-kpi__spark--green" />
          </div>
        </div>

        {/* ── Main grid ── */}
        <div className="gc-grid gc-grid--sidebar">

          {/* Left */}
          <div style={{ display: "flex", flexDirection: "column", gap: "16px" }}>

            {/* Live Revenue Feed */}
            <div className="gc-card gc-reveal">
              <div className="gc-card__header">
                <span className="gc-card__title">Live Stripe Revenue Feed</span>
                <span className="gc-badge gc-badge--live gc-badge--dot">Real-time</span>
              </div>
              <div className="gc-card__body" style={{ padding: 0 }}>
                {recentEvents.length === 0 ? (
                  <div style={{ padding: "32px 22px", textAlign: "center", color: "var(--gc-text-3)", fontFamily: "var(--gc-font-mono)", fontSize: "0.82rem" }}>
                    Waiting for first Stripe event…<br />
                    <span style={{ color: "var(--gc-text-3)", fontSize: "0.72rem", marginTop: "8px", display: "block" }}>
                      Register webhook at dashboard.stripe.com/webhooks → {webhookUrl}
                    </span>
                  </div>
                ) : (
                  <table className="gc-table">
                    <thead>
                      <tr>
                        <th>Event</th>
                        <th>Customer</th>
                        <th>Product</th>
                        <th style={{ textAlign: "right" }}>Amount</th>
                        <th>When</th>
                      </tr>
                    </thead>
                    <tbody>
                      {recentEvents.map((evt: any) => (
                        <tr key={evt.id}>
                          <td>
                            <span className={`gc-badge ${eventBadgeClass(evt.eventType)}`}>
                              {eventLabel(evt.eventType)}
                            </span>
                          </td>
                          <td style={{ fontFamily: "var(--gc-font-mono)", fontSize: "0.75rem" }}>
                            {evt.customerEmail ?? evt.customerId ?? "—"}
                          </td>
                          <td style={{ color: "var(--gc-text)" }}>{evt.productName ?? "—"}</td>
                          <td className="gc-table__amount" style={{
                            textAlign: "right",
                            color: parseFloat(evt.amountDollars) < 0 ? "var(--gc-red)" : "var(--gc-emerald)",
                          }}>
                            {parseFloat(evt.amountDollars) < 0 ? "-" : "+"}${Math.abs(parseFloat(evt.amountDollars)).toFixed(2)} {evt.currency}
                          </td>
                          <td style={{ fontFamily: "var(--gc-font-mono)", fontSize: "0.72rem", color: "var(--gc-text-3)" }}>
                            {new Date(evt.createdAt).toLocaleDateString("en-US",{month:"short",day:"numeric",hour:"2-digit",minute:"2-digit"})}
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                )}
              </div>
            </div>

            {/* Revenue Stack Table */}
            <div className="gc-card gc-reveal">
              <div className="gc-card__header">
                <span className="gc-card__title">Revenue Stack — All 12 Systems</span>
                <span className="gc-badge gc-badge--info">$155K+ ARR Target</span>
              </div>
              <div className="gc-card__body" style={{ padding: 0 }}>
                <table className="gc-table">
                  <thead>
                    <tr>
                      <th>System</th>
                      <th>Model</th>
                      <th>Status</th>
                      <th style={{ textAlign: "right" }}>MRR Target</th>
                    </tr>
                  </thead>
                  <tbody>
                    {revenueProducts.map((p, i) => (
                      <tr key={i}>
                        <td style={{ color: "var(--gc-text)" }}>{p.name}</td>
                        <td>{p.model}</td>
                        <td><span className={`gc-badge gc-badge--${p.status === "live" ? "live" : "build"} gc-badge--dot`}>{p.status === "live" ? "Live" : "Building"}</span></td>
                        <td className="gc-table__amount" style={{ textAlign: "right" }}>${p.mrr.toLocaleString()}</td>
                      </tr>
                    ))}
                  </tbody>
                  <tfoot>
                    <tr className="gc-table__total">
                      <td colSpan={3}><strong>Combined Monthly Target</strong></td>
                      <td className="gc-table__amount" style={{ textAlign: "right" }}>${metrics.arTarget.toLocaleString()}+</td>
                    </tr>
                  </tfoot>
                </table>
              </div>
            </div>

            {/* Quick Actions */}
            <div className="gc-card gc-reveal">
              <div className="gc-card__header">
                <span className="gc-card__title">Quick Actions</span>
              </div>
              <div className="gc-card__body" style={{ display: "flex", gap: "12px", flexWrap: "wrap" }}>
                <fetcher.Form method="POST">
                  <input type="hidden" name="intent" value="generate_product" />
                  <button type="submit" className={`gc-btn gc-btn--primary${loading ? " gc-btn--loading" : ""}`}>
                    {loading ? "⟳ Generating…" : "⚡ Generate AI Product"}
                  </button>
                </fetcher.Form>
                <a href="https://dashboard.stripe.com/webhooks" target="_blank" rel="noopener noreferrer" className="gc-btn gc-btn--ghost">
                  Stripe Webhooks →
                </a>
                <a href="https://dashboard.stripe.com/payments" target="_blank" rel="noopener noreferrer" className="gc-btn gc-btn--ghost">
                  Stripe Payments →
                </a>
                <a href="https://github.com/Garrettc123/garcar-shopify-app" target="_blank" rel="noopener noreferrer" className="gc-btn gc-btn--ghost">
                  GitHub →
                </a>
              </div>
              {product && (
                <div className="gc-card__body" style={{ paddingTop: 0 }}>
                  <div className="gc-result-box">
                    ✅ Product created: <strong>{product.title}</strong>
                  </div>
                </div>
              )}
            </div>
          </div>

          {/* Right Sidebar */}
          <div style={{ display: "flex", flexDirection: "column", gap: "16px" }}>

            {/* Webhook Setup Card */}
            <div className="gc-card gc-reveal" style={{ borderColor: "rgba(0,255,136,0.2)" }}>
              <div className="gc-card__header">
                <span className="gc-card__title">Stripe Webhook Setup</span>
                <span className="gc-badge gc-badge--live gc-badge--dot">Wired</span>
              </div>
              <div className="gc-card__body">
                <div className="gc-status-list">
                  <div className="gc-status-row">
                    <span className="gc-status-name"><span className="gc-status-dot gc-status-dot--on"/>Endpoint</span>
                    <span className="gc-status-val">/webhooks/stripe</span>
                  </div>
                  <div className="gc-status-row">
                    <span className="gc-status-name"><span className="gc-status-dot gc-status-dot--on"/>HMAC Verify</span>
                    <span className="gc-status-val">SHA-256 ✅</span>
                  </div>
                  <div className="gc-status-row">
                    <span className="gc-status-name"><span className="gc-status-dot gc-status-dot--on"/>Idempotency</span>
                    <span className="gc-status-val">stripeEventId</span>
                  </div>
                </div>
                <div style={{ marginTop: "16px" }}>
                  <div style={{ fontSize: "0.68rem", fontFamily: "var(--gc-font-mono)", color: "var(--gc-text-3)", marginBottom: "8px", textTransform: "uppercase", letterSpacing: "0.1em" }}>
                    Events Handled
                  </div>
                  {[
                    "checkout.session.completed",
                    "invoice.payment_succeeded",
                    "invoice.payment_failed",
                    "customer.subscription.created",
                    "customer.subscription.updated",
                    "customer.subscription.deleted",
                    "charge.refunded",
                  ].map(e => (
                    <div key={e} style={{ fontSize: "0.72rem", fontFamily: "var(--gc-font-mono)", color: "var(--gc-text-2)", padding: "3px 0", borderBottom: "1px solid var(--gc-border)" }}>
                      → {e}
                    </div>
                  ))}
                </div>
                <div style={{ marginTop: "16px", padding: "10px 12px", background: "var(--gc-bg3)", borderRadius: "8px", fontFamily: "var(--gc-font-mono)", fontSize: "0.7rem", color: "var(--gc-text-3)", wordBreak: "break-all" }}>
                  {webhookUrl}
                </div>
              </div>
            </div>

            {/* Store Info */}
            <div className="gc-card gc-reveal">
              <div className="gc-card__header">
                <span className="gc-card__title">Store</span>
                <span className="gc-badge gc-badge--live gc-badge--dot">Connected</span>
              </div>
              <div className="gc-card__body">
                <div className="gc-status-list">
                  {[
                    { label: "Name",     val: shop?.name },
                    { label: "Plan",     val: shop?.plan?.displayName },
                    { label: "Currency", val: shop?.currencyCode },
                    { label: "Domain",   val: shop?.primaryDomain?.url?.replace("https://","") },
                    { label: "Products", val: String(metrics.shopifyProducts) },
                    { label: "Orders",   val: String(metrics.shopifyOrders) + " paid" },
                  ].map((r, i) => (
                    <div key={i} className="gc-status-row">
                      <span className="gc-status-name">{r.label}</span>
                      <span className="gc-status-val">{r.val || "—"}</span>
                    </div>
                  ))}
                </div>
              </div>
            </div>

            {/* System Status */}
            <div className="gc-card gc-reveal">
              <div className="gc-card__header">
                <span className="gc-card__title">System Status</span>
              </div>
              <div className="gc-card__body">
                <div className="gc-status-list">
                  {[
                    { label: "Stripe Webhook",   state:"on",   val:"Live · HMAC ✅" },
                    { label: "MRR Tracking",     state:"on",   val:"Prisma · Real-time" },
                    { label: "Subscription Sync",state:"on",   val:"Auto-upsert" },
                    { label: "Refund Handling",  state:"on",   val:"Negative events" },
                    { label: "Idempotency",      state:"on",   val:"stripeEventId key" },
                    { label: "OAuth",            state:"on",   val:"Active" },
                    { label: "Admin GraphQL",    state:"on",   val:"2026-01" },
                    { label: "Churn Predictor",  state:"on",   val:"Vercel · Live" },
                    { label: "Deal Desk AI",     state:"on",   val:"Vercel · Live" },
                    { label: "Content Engine",   state:"on",   val:"Vercel · Live" },
                    { label: "GitHub CI",        state:"on",   val:"Passing" },
                    { label: "Stripe Compliance",state:"warn", val:"Due Apr 14" },
                    { label: "garcar.ai DNS",    state:"off",  val:"NXDOMAIN" },
                  ].map((s, i) => (
                    <div key={i} className="gc-status-row">
                      <span className="gc-status-name">
                        <span className={`gc-status-dot gc-status-dot--${s.state}`} />
                        {s.label}
                      </span>
                      <span className="gc-status-val">{s.val}</span>
                    </div>
                  ))}
                </div>
              </div>
            </div>

            {/* Live MRR Hero */}
            <div className="gc-card gc-reveal" style={{ background: "rgba(0,255,136,0.03)", borderColor: "rgba(0,255,136,0.2)" }}>
              <div className="gc-card__body" style={{ textAlign: "center", padding: "28px 22px" }}>
                <div style={{ fontFamily: "var(--gc-font-mono)", fontSize: "0.65rem", color: "var(--gc-text-3)", textTransform: "uppercase", letterSpacing: "0.14em", marginBottom: "6px" }}>
                  Stripe MRR · This Month
                </div>
                <div style={{ fontFamily: "var(--gc-font-display)", fontSize: "2.6rem", fontWeight: 900, color: "var(--gc-emerald)", letterSpacing: "-0.04em", lineHeight: 1 }}>
                  <span ref={el => { cRefs.current.mrrDollars2 = el as any; }}>
                    ${metrics.mrrDollars}
                  </span>
                </div>
                <div style={{ fontSize: "0.72rem", color: "var(--gc-text-3)", marginTop: "10px", fontFamily: "var(--gc-font-mono)" }}>
                  {metrics.activeSubs} active sub{metrics.activeSubs !== 1 ? "s" : ""} · all-time ${metrics.allTimeDollars}
                </div>
                <div style={{ marginTop: "16px", height: "1px", background: "var(--gc-border)" }} />
                <div style={{ marginTop: "14px", fontSize: "0.72rem", color: "var(--gc-text-3)" }}>
                  ARR target: <span style={{ color: "var(--gc-emerald)", fontWeight: 700 }}>${metrics.arTarget.toLocaleString()}/yr</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
